=== walidmouatamid/xml/biblio.dtd
<!ELEMENT biblio (livre*) >
<!ELEMENT livre (ISBN,auteur+,titre,resume,date_publication) >
<!ATTLIST livre categorie CDATA #REQUIRED  >
<!ATTLIST livre langue (fr|en|ar|es) #REQUIRED>
<!ELEMENT ISBN (#PCDATA) >
<!ELEMENT auteur (nom,identifiant,identificateurs_publication) >
<!ELEMENT nom (#PCDATA) >
<!ELEMENT identifiant (#PCDATA) >
<!ELEMENT identificateurs_publication (id_pub+) >
<!ELEMENT id_pub (#PCDATA) >
<!ELEMENT titre (#PCDATA) >
<!ELEMENT resume (#PCDATA) >
<!ELEMENT date_publication (#PCDATA) >

=== walidmouatamid/xml/biblio.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE   biblio SYSTEM "biblio.dtd">
<biblio>
    <livre categorie="info" langue="fr">
        <ISBN></ISBN>   
        <auteur>
            <nom></nom>
            <identifiant></identifiant>
            <identificateurs_publication>
                <id_pub></id_pub>
                <id_pub></id_pub>
            </identificateurs_publication>
        </auteur>
        <titre></titre>
        <resume></resume>
        <date_publication></date_publication>
    </livre>
</biblio>
